### ISSUE TITLE
Will this support Symfony 4?

### ISSUE THREAD

**Issue by simPod** [UselessSoft/queries-doctrine#1]
> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should alias the "UselessSoft\Queries\Doctrine\Queryable" service to "UselessSoft\Queries\Doctrine\QueryableInterface" instead.

Thanks!

**Comment by Majkl578** [comment]
Symfony 4 compatibility should be ready in master.

Issue at wrong repository, should be at :https://github.com/UselessSoft/queries-bundle
